[package]
name = "gpu-monitor"
version = "0.1.0"
authors = ["Pim de Haan <pimdehaan@gmail.com>"]

[dependencies]
csv = "1"
serde = "1.0"
serde_derive = "1.0"
regex = "1"
lazy_static = "1.1.0"
prettytable-rs = "^0.7"
